on:
  push:
    branches: [ "main", "preview" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js / yarn
      uses: mskelton/setup-yarn@v1

    - name: yarn install
      run: |
        yarn
        
    # - name: build and deploy
    #   run: |
    #     yarn build

    - name: Azure Static Web Apps Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        # Action to perform
        action: "upload"
        # Directory location of the application source code
        app_location: "/"
        azure_static_web_apps_api_token: ${{ secrets.SWA_CLI_DEPLOYMENT_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Custom command for Oryx to run when building Azure Functions source code
        # api_build_command: "yarn build"
        # Directory location of the Azure Functions source code
        api_location: "build/server"
        # Directory location of the compiled application code after building
        output_location: "build/static"
        skip_deploy_on_missing_secrets: true
        skip_app_build: true
